---
include: https://raw.githubusercontent.com/hassio-addons/organization/master/gitlabci/addon.yml

variables:
  ADDON_GITHUB_REPO: "hassio-addons/addon-firefly-iii"
  ADDON_SLUG: "firefly-iii"
  ADDON_TARGET: "firefly-iii"
  ADDON_LEGACY_TAGS: "true"
  ADDON_ARMHF: "false"

  ADDON_AARCH64_BASE: "hassioaddons/debian-base-aarch64:3.2.3"
  ADDON_AMD64_BASE: "hassioaddons/debian-base-amd64:3.2.3"
  ADDON_ARMV7_BASE: "hassioaddons/debian-base-armv7:3.2.3"
  ADDON_I386_BASE: "hassioaddons/debian-base-i386:3.2.3"
