---
build_from:
  armv7: "ghcr.io/hassio-addons/debian-base/arm32v7:5.3.1"
  armhf: "ghcr.io/hassio-addons/debian-base/armhf:5.3.1"
  aarch64: "ghcr.io/hassio-addons/debian-base/aarch64:5.3.1"
  amd64: "ghcr.io/hassio-addons/debian-base/amd64:5.3.1"
  i386: "ghcr.io/hassio-addons/debian-base/i386:5.3.1"
