---
build_from:
  armv7: "ghcr.io/hassio-addons/debian-base/arm32v7:"
  armhf: "ghcr.io/hassio-addons/debian-base/armhf:"
  aarch64: "ghcr.io/hassio-addons/debian-base/aarch64:"
  amd64: "ghcr.io/hassio-addons/debian-base/amd64:5.3.1"
  i386: "ghcr.io/hassio-addons/debian-base/i386:"
