name: Docker Image CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_ARCH: amd64
    steps:
    - uses: actions/checkout@v2
    - uses: chrisdickinson/setup-yq@latest
    - name: set env vars with build.yaml
      run: |
        echo "build_from=$(yq r firefly-iii/build.yaml build_from.${{ env.BUILD_ARCH }})" >> $GITHUB_ENV
        echo "firefly_version=$(yq r firefly-iii/build.yaml args.FIREFLY_VERSION)" >> $GITHUB_ENV
        echo "bashio_version=$(yq r firefly-iii/build.yaml args.BASHIO_VERSION)" >> $GITHUB_ENV
        echo "tempio_version=$(yq r firefly-iii/build.yaml args.TEMPIO_VERSION)" >> $GITHUB_ENV
        echo "s6_overlay_version=$(yq r firefly-iii/build.yaml args.S6_OVERLAY_VERSION)" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build firefly-iii --file firefly-iii/Dockerfile --build-arg BUILD_FROM=${{ env.build_from }} --build-arg BUILD_ARCH=${{ env.BUILD_ARCH }} --build-arg FIREFLY_VERSION=${{ env.firefly_version }} --build-arg BASHIO_VERSION=${{ env.bashio_version }} --build-arg TEMPIO_VERSION=${{ env.tempio_version }} --build-arg S6_OVERLAY_VERSION=${{ env.s6_overlay_version }} --tag coostax/ha-addon-firefly-iii:$(date +%s)
